import { Roboto } from "next/font/google";
import Nav from "@/components/Nav/Nav";
import StoreProvider from "./StoreProvider";
import GloballyDispatch from "./GloballyDispatch";
import "./globals.css";
import SessionProviders from "./SessionProviders";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProviders>
      <html lang="en">
        <body className={roboto.className}>
          <StoreProvider>
            <GloballyDispatch>
              <Nav />
              {children}
            </GloballyDispatch>
          </StoreProvider>
        </body>
      </html>
    </SessionProviders>
  );
}
